"""create players table

Revision ID: 89ee0813931e
Revises: 
Create Date: 2021-02-05 18:00:39.820969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89ee0813931e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column(
        'first_name', sa.String(length=255), nullable=True))
    op.add_column('players', sa.Column(
        'full_name', sa.String(length=255), nullable=True))
    op.add_column('players', sa.Column(
        'last_name', sa.String(length=255), nullable=True))
    op.add_column('players', sa.Column(
        'nba_player_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'nba_player_id')
    op.drop_column('players', 'last_name')
    op.drop_column('players', 'full_name')
    op.drop_column('players', 'first_name')
    # ### end Alembic commands ###
